### ISSUE TITLE
Installed but does not show in GUI

### ISSUE THREAD

**Issue by RealTekHousE** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#13]
I get this error. I see the extension in the list inside of A1111, but there is no menu item.

Loading model stabilityai/stable-diffusion-xl-base-0.9
*** Error loading script: sd_webui_xldemo_txt2img.py
    Traceback (most recent call last):
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 3, in <module>
        from xldemo_txt2img_ui import make_ui
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 6, in <module>
        from xldemo_txt2img import XLDEMO_HUGGINGFACE_ACCESS_TOKEN, XLDEMO_LOAD_REFINER_ON_STARTUP
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 177, in <module>
        xldemo_txt2img = XLDemo()
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 72, in __init__
        self.pipe = DiffusionPipeline.from_pretrained(
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 884, in from_pretrained
        cached_folder = cls.download(
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1265, in download
        pipeline_class = _get_pipeline_class(
      File "F:\stable-diffusion\Launcher\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 344, in _get_pipeline_class
        return getattr(diffusers_module, config["_class_name"])
    AttributeError: module 'diffusers' has no attribute 'StableDiffusionXLPipeline'

**Comment by lifeisboringsoprogramming** [comment]
I think some other extension has installed a diffusers package that is lower than the version 0.18.1
You may try to disable those extensions

**Comment by IntellectzProductions** [comment]
Ok, Here is how to fix this issue. If you have Dreambooth as one of your extensions, Automatic 1111 uses 0.16.1 Diffusers. All you have to do is go into the requirements.txt for Dreambooth and change that to 0.18.1. Save it and then restart the Webui. When it comes back up the models will start downloading. I will report if Dreambooth disappears or not.

**Comment by RealTekHousE** [comment]
Trying this now..Will report back Tx mate!

**Comment by RealTekHousE** [comment]
Yes that worked. I will do some more testing. But both your extension and Dreambooth are showing in the menus.
