### ISSUE TITLE
AttributeError: 'list' object has no attribute 'translate'

### ISSUE THREAD

**Issue by swumagic** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#15]
*** Error adding [prompt_spaces] to filename
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\images.py", line 462, in apply
        replacement = fun(self, *pattern_args)
      File "M:\SD\sdwebui\modules\images.py", line 367, in <lambda>
        'prompt_spaces': lambda self: sanitize_filename_part(self.prompt, replace_spaces=False),
      File "M:\SD\sdwebui\modules\images.py", line 332, in sanitize_filename_part
        text = text.translate({ord(x): '_' for x in invalid_filename_chars})
    AttributeError: 'list' object has no attribute 'translate'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
2023-07-13 02:44:57,367 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
2023-07-13 02:44:57,372 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
*** Error adding [prompt_spaces] to filename
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\images.py", line 462, in apply
        replacement = fun(self, *pattern_args)
      File "M:\SD\sdwebui\modules\images.py", line 367, in <lambda>
        'prompt_spaces': lambda self: sanitize_filename_part(self.prompt, replace_spaces=False),
      File "M:\SD\sdwebui\modules\images.py", line 332, in sanitize_filename_part
        text = text.translate({ord(x): '_' for x in invalid_filename_chars})
    AttributeError: 'list' object has no attribute 'translate'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by lifeisboringsoprogramming** [comment]
what did you do? how to reproduce the problem?

**Comment by swumagic** [comment]
I input the prompt word, and then two errors are displayed like this, but the picture can still be drawn after waiting 8 minutes, that is, there is the above error prompt.

**Comment by swumagic** [comment]
2023-07-13 02:37:38,834 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
2023-07-13 02:37:38,839 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
2023-07-13 02:37:45,842 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
2023-07-13 02:37:45,848 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
2023-07-13 02:41:23,119 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
2023-07-13 02:41:23,125 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
*** Error adding [prompt_spaces] to filename
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\images.py", line 462, in apply
        replacement = fun(self, *pattern_args)
      File "M:\SD\sdwebui\modules\images.py", line 367, in <lambda>
        'prompt_spaces': lambda self: sanitize_filename_part(self.prompt, replace_spaces=False),
      File "M:\SD\sdwebui\modules\images.py", line 332, in sanitize_filename_part
        text = text.translate({ord(x): '_' for x in invalid_filename_chars})
    AttributeError: 'list' object has no attribute 'translate'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
2023-07-13 02:44:57,367 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
2023-07-13 02:44:57,372 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
*** Error adding [prompt_spaces] to filename
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\images.py", line 462, in apply
        replacement = fun(self, *pattern_args)
      File "M:\SD\sdwebui\modules\images.py", line 367, in <lambda>
        'prompt_spaces': lambda self: sanitize_filename_part(self.prompt, replace_spaces=False),
      File "M:\SD\sdwebui\modules\images.py", line 332, in sanitize_filename_part
        text = text.translate({ord(x): '_' for x in invalid_filename_chars})
    AttributeError: 'list' object has no attribute 'translate'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by swumagic** [comment]
I input the prompt word： best quality, masterpiece,1girl,indoors,nsfw。and then two errors are displayed like this

**Comment by swumagic** [comment]
Settings > Saving images/grids > [wiki] filename pattern > enter "[seed]" and tick "add number to filename while saving."

You will get filenames like 0001 9384948.png with the parameters/prompts/etc. embedded in the file, you can check them using PNG Info. (I right-click the images I want to keep and use "save as" anyway.)  @bjornlarssen
