### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by amrsabry-ai** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#26]
I have 16 GB rtx4080 and ram 64 but not working .. after (install from url ) and update and restart and restart webui also but not appear at tabs  

how to fix it please ??
![Screenshot 2023-07-16 033451](https://github.com/lifeisboringsoprogramming/sd-webui-xldemo-txt2img/assets/131651946/a1419030-20dc-4346-95b1-934ae7f0cad4)
![Screenshot 2023-07-16 033531](https://github.com/lifeisboringsoprogramming/sd-webui-xldemo-txt2img/assets/131651946/536c5b4b-ec24-4d55-8594-9cf9d43a7ce9)

**Comment by ganeshkrishnan1** [comment]
same issue here. Just installed and the menu for token is not visible anywhere

**Comment by lifeisboringsoprogramming** [comment]
did you see any error messages from the console?

**Comment by wqjuser** [comment]
Error loading script: sd_webui_xldemo_txt2img.py
    Traceback (most recent call last):
      File "G:\WEBUI\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\WEBUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\WEBUI\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 4, in <module>
        from xldemo_txt2img_ui import make_ui
      File "G:\WEBUI\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 7, in <module>
        from xldemo_txt2img import XLDEMO_HUGGINGFACE_ACCESS_TOKEN, XLDEMO_LOAD_REFINER_ON_STARTUP
      File "G:\WEBUI\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 19, in <module>
        from diffusers.schedulers.scheduling_dpmsolver_sde import DPMSolverSDEScheduler as dpmsolver_sde
    ModuleNotFoundError: No module named 'diffusers.schedulers.scheduling_dpmsolver_sde'

**Comment by lifeisboringsoprogramming** [comment]
I think some other extension installed a diffusers version lower than 0.18.1

**Comment by wqjuser** [comment]
i have update diffusers to 0.18.2，but still have the same error

**Comment by lifeisboringsoprogramming** [comment]
It is not the version in extensions/sd-webui-xldemo-txt2img/requirements_webui.txt

If you have other extensions installed

They may install another version of diffusers and it will overwrite your diffusers version

**Comment by amrsabry-ai** [comment]
> I think some other extension installed a diffusers version lower than 0.18.1

![Uploading Screenshot 2023-07-16 222451.png…]()

**Comment by H1ghSyst3m** [comment]
Same Problem:

*** Error loading script: sd_webui_xldemo_txt2img.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 4, in <module>
        from xldemo_txt2img_ui import make_ui
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 7, in <module>
        from xldemo_txt2img import XLDEMO_HUGGINGFACE_ACCESS_TOKEN, XLDEMO_LOAD_REFINER_ON_STARTUP
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 19, in <module>
        from diffusers.schedulers.scheduling_dpmsolver_sde import DPMSolverSDEScheduler as dpmsolver_sde
    ModuleNotFoundError: No module named 'diffusers.schedulers.scheduling_dpmsolver_sde'
    
    I already reinstalled and restarted A1111, I also manually installed the requiements.

**Comment by lifeisboringsoprogramming** [comment]
try just using the sd-webui-xldemo-txt2img extension without any others
