### ISSUE TITLE
Error after installing the extension

### ISSUE THREAD

**Issue by JadeHMD** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#29]
Should I need to update Python? Or what is the actual problem? I just see that the extension can't find a module.

*** Error loading script: sd_webui_xldemo_txt2img.py
    Traceback (most recent call last):
      File "C:\Stable-Diffusion_NEW\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Stable-Diffusion_NEW\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Stable-Diffusion_NEW\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 4, in <module>
        from xldemo_txt2img_ui import make_ui
      File "C:\Stable-Diffusion_NEW\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 7, in <module>
        from xldemo_txt2img import XLDEMO_HUGGINGFACE_ACCESS_TOKEN, XLDEMO_LOAD_REFINER_ON_STARTUP
      File "C:\Stable-Diffusion_NEW\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 19, in <module>
        from diffusers.schedulers.scheduling_dpmsolver_sde import DPMSolverSDEScheduler as dpmsolver_sde
    ModuleNotFoundError: No module named 'diffusers.schedulers.scheduling_dpmsolver_sde'

---

Thanks for help!

**Comment by lifeisboringsoprogramming** [comment]
I think some other extension installed a diffusers version lower than 0.18.1

**Comment by mrvirus9898** [comment]
Its the DreamBooth Extension. It is forcing 16.1 instead of using the latest 18.2. I will head over to the Dreambooth folks and raise a compatibility issue. In the meantime, disable Dreambooth.

**Comment by mrvirus9898** [comment]
UPDATE: Raised issue with Dreambooth. In the mean time you can:

go to stable-diffusion-webui\extensions\sd_dreambooth_extension
Open requirements.txt
go to line 4, should say "diffusers~=0.16.1"
change line 4 to "diffusers~=0.18.2"
save file, close
Restart WebUI if it is open.

Not sure if this will do anything to Dreambooth, but it will get SDXL working. Should not effect Dreambooth, but this is not tested. This method can work for other extensions as well, check their requirements, and see if they are using an old Diffusers version.
