### ISSUE TITLE
Tab disappears after following the instructions

### ISSUE THREAD

**Issue by Razeshi** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#31]
I followed the instructions in the tab, but then it disappeared...the only thing telling me I still have the extension installed is that it still shows in the extensions tab.

**Comment by lifeisboringsoprogramming** [comment]
do you have a screenshot and the console messages?

**Comment by Razeshi** [comment]
*** Error loading script: sd_webui_xldemo_txt2img.py

    Traceback (most recent call last):

      File "C:\Stable Diffusion AI\modules\scripts.py", line 274, in load_scripts

        script_module = script_loading.load_module(scriptfile.path)

      File "C:\Stable Diffusion AI\modules\script_loading.py", line 10, in load_module

        module_spec.loader.exec_module(module)

      File "<frozen importlib._bootstrap_external>", line 883, in exec_module

      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

      File "C:\Stable Diffusion AI\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 4, in <module>

        from xldemo_txt2img_ui import make_ui

      File "C:\Stable Diffusion AI\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 7, in <module>

        from xldemo_txt2img import XLDEMO_HUGGINGFACE_ACCESS_TOKEN, XLDEMO_LOAD_REFINER_ON_STARTUP

      File "C:\Stable Diffusion AI\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 19, in <module>

        from diffusers.schedulers.scheduling_dpmsolver_sde import DPMSolverSDEScheduler as dpmsolver_sde

    ModuleNotFoundError: No module named 'diffusers.schedulers.scheduling_dpmsolver_sde'

 

This?

 

Von: Life is boring, so programming ***@***.***> 
Gesendet: Sonntag, 16. Juli 2023 20:45
An: lifeisboringsoprogramming/sd-webui-xldemo-txt2img ***@***.***>
Cc: Razeshi ***@***.***>; Author ***@***.***>
Betreff: Re: [lifeisboringsoprogramming/sd-webui-xldemo-txt2img] Tab disappears after following the instructions (Issue #31)

 

do you have a screenshot and the console messages?

**Comment by lifeisboringsoprogramming** [comment]
I think some other extension installed a diffusers version lower than 0.18.1

**Comment by Razeshi** [comment]
Can you tell me how to identify this  extension? Sorry, I am inexperienced.

 

Von: Life is boring, so programming ***@***.***> 
Gesendet: Sonntag, 16. Juli 2023 23:52
An: lifeisboringsoprogramming/sd-webui-xldemo-txt2img ***@***.***>
Cc: Razeshi ***@***.***>; Author ***@***.***>
Betreff: Re: [lifeisboringsoprogramming/sd-webui-xldemo-txt2img] Tab disappears after following the instructions (Issue #31)

 

I think some other extension installed a diffusers version lower than 0.18.1

**Comment by lifeisboringsoprogramming** [comment]
The easiest way is to disable other extensions

**Comment by thegreatsai** [comment]
Current Dreambooth uses lower version than 0.18.1. Disable that extension and SDXL will fire up.

**Comment by Yoke-pixel** [comment]
I have the same issue tab disappears. I have diffusers version 0.18.1 installed. Also no Dreambooth installed.
![Tab](https://github.com/lifeisboringsoprogramming/sd-webui-xldemo-txt2img/assets/122103442/eced7013-7bc3-427b-bd6f-62f1e9a37231)

**Comment by CaptDoodle** [comment]
> I have the same issue tab disappears. I have diffusers version 0.18.1 installed. Also no Dreambooth installed. ![Tab](https://user-images.githubusercontent.com/122103442/257737491-eced7013-7bc3-427b-bd6f-62f1e9a37231.JPG)

I am also getting the same issue:
Error executing callback ui_tabs_callback for C:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 9, in on_ui_tabs
    return [(make_ui(), "SDXL Demo", "xldemo_txt2img")]
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 96, in make_ui
    xldemo_txt2img_seed, xldemo_txt2img_reuse_seed = create_seed_inputs(id_part)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui_common.py", line 30, in create_seed_inputs
    random_seed = ToolButton(
TypeError: ToolButton.__init__() takes 1 positional argument but 2 were given

**Comment by lifeisboringsoprogramming** [comment]
what is the webui version?

**Comment by lifeisboringsoprogramming** [comment]
please update and try again

**Comment by CaptDoodle** [comment]
> please update and try again

Thanks, forced update resolved the issue

**Comment by Yoke-pixel** [comment]
I just updated, same issue persist.  What you mean by "forced update" ?

**Comment by lifeisboringsoprogramming** [comment]
try run the webUI with just this extension
