### ISSUE TITLE
diffusion_pytorch_model.safetensors and text_encoder_2\model.safetensors not found

### ISSUE THREAD

**Issue by trxsudo** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#37]
Launching Web UI with arguments: --theme dark --xformers --no-half-vae --api --autolaunch
Using SDXL 0.9
Loading model stabilityai/stable-diffusion-xl-base-0.9
vae\diffusion_pytorch_model.safetensors not found
Loading model stabilityai/stable-diffusion-xl-refiner-0.9
text_encoder_2\model.safetensors not found
Loading weights [ed989d673d] from D:\sd\sd-webui-aki-v4.1\models\Stable-diffusion\dreamshaper_7.safetensors
Running on local URL:  http://127.0.0.1:7860

**above were lines when lauching the webui. the weights were all downloaded, but after restarting,  the console gives me safetensors not found error.**

**by typing in txt in the prompt section, the image can be generated, but console is still showing error as follows:**

Model loaded in 6.5s (load weights from disk: 0.6s, create model: 0.9s, apply weights to model: 2.8s, apply half(): 0.5s, load VAE: 0.7s, move model to device: 0.9s, load textual inversion embeddings: 0.1s).
Error adding [prompt_spaces] to filename
Traceback (most recent call last):
  File "D:\sd\sd-webui-aki-v4.1\modules\images.py", line 446, in apply
    replacement = fun(self, *pattern_args)
  File "D:\sd\sd-webui-aki-v4.1\modules\images.py", line 355, in <lambda>
    'prompt_spaces': lambda self: sanitize_filename_part(self.prompt, replace_spaces=False),
  File "D:\sd\sd-webui-aki-v4.1\modules\images.py", line 332, in sanitize_filename_part
    text = text.translate({ord(x): '_' for x in invalid_filename_chars})
AttributeError: 'list' object has no attribute 'translate'

not sure what is going on here. need some pointers.

**Comment by lifeisboringsoprogramming** [comment]
some users use different Images filename pattern and have the same errors
