### ISSUE TITLE
Startup error: missing models, tab missing too.

### ISSUE THREAD

**Issue by ch1ckenstripper** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#5]
I would just download them myself but idk where to put them exactly. is there a mismatch somewhere? THANKS

Loading model stabilityai/stable-diffusion-xl-base-0.9
vae\diffusion_pytorch_model.safetensors not found
*** Error loading script: sd_webui_xldemo_txt2img.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 3, in <module>
        from xldemo_txt2img_ui import make_ui
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 6, in <module>
        from xldemo_txt2img import XLDEMO_HUGGINGFACE_ACCESS_TOKEN, XLDEMO_LOAD_REFINER_ON_STARTUP
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 144, in <module>
        xldemo_txt2img = XLDemo()
      File "E:\AI\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 56, in __init__
        self.pipe = DiffusionPipeline.from_pretrained(
      File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 882, in from_pretrained
        cached_folder = cls.download(
      File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1260, in download
        raise EnvironmentError(
    OSError: Could not found the necessary `safetensors` weights in {'unet/diffusion_pytorch_model.safetensors', 'vae/diffusion_pytorch_model.safetensors', 'vae/diffusion_pytorch_model.bin', 'unet/diffusion_pytorch_model.bin', 'text_encoder/model.safetensors', 'text_encoder_2/pytorch_model.bin', 'text_encoder/pytorch_model.bin', 'text_encoder_2/model.safetensors'} (variant=None)

---

**Comment by poluramus** [comment]
I have the same error... 👎. Let me know if you solve the problem sir !

**Comment by IntellectzProductions** [comment]
I have the same issue. It started to work at first. It showed up then after the restart. I got a bunch of errors and Auto1111 kept failing to download the model. I tried for 2 hours and just gave up. I never got to the point of where I saw the tab

**Comment by poluramus** [comment]
Same for me. I'm not enough of a wizard in AI to figured it out 🤣

**Comment by lifeisboringsoprogramming** [comment]
[Windows Users]
This is my testing environment of my Windows 10 machine
Nvidia driver version 536.40  
GPU: RTX3060 12G VRAM

If you want to try

1) Please remove the 
models--stabilityai--stable-diffusion-xl-base-0.9 and 
models--stabilityai--stable-diffusion-xl-refiner-0.9 folders 
under the path 
C:\Users\username\.cache\huggingface\hub
But this should have no weights inside

2) Update the extension from the Web UI

3) Restart Web UI

4) The weights should automatically downloaded to the path 
C:\Users\username\.cache\huggingface\hub

5) If everything's okay, you can play with it

**Comment by Etreumze** [comment]
followed the steps, updated the extension still same problem.

Loading model stabilityai/stable-diffusion-xl-base-0.9
Downloading (…)ain/model_index.json: 100%|████████████████████████████████████████████████████| 582/582 [00:00<?, ?B/s]
*** Error loading script: sd_webui_xldemo_txt2img.py
    Traceback (most recent call last):
      File "F:\AI-Image\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\AI-Image\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\AI-Image\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\scripts\sd_webui_xldemo_txt2img.py", line 3, in <module>
        from xldemo_txt2img_ui import make_ui
      File "F:\AI-Image\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img_ui.py", line 6, in <module>
        from xldemo_txt2img import XLDEMO_HUGGINGFACE_ACCESS_TOKEN, XLDEMO_LOAD_REFINER_ON_STARTUP
      File "F:\AI-Image\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 144, in <module>
        xldemo_txt2img = XLDemo()
      File "F:\AI-Image\stable-diffusion-webui\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 56, in __init__
        self.pipe = DiffusionPipeline.from_pretrained(
      File "F:\AI-Image\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 884, in from_pretrained
        cached_folder = cls.download(
      File "F:\AI-Image\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1265, in download
        pipeline_class = _get_pipeline_class(
      File "F:\AI-Image\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 344, in _get_pipeline_class
        return getattr(diffusers_module, config["_class_name"])
    AttributeError: module 'diffusers' has no attribute 'StableDiffusionXLPipeline'

---

**Comment by MetalOctopus** [comment]
Confirming I have downloaded the weights, but the path to diffusion_pytorch_model.bin is:
\Users\\[user]\.cache\huggingface\hub\models--stabilityai--stable-diffusion-xl-base-0.9\snapshots\\[string]\unet\

Error returned is now the same as Etreumze has posted:
> *** Error loading script: sd_webui_xldemo_txt2img.py
[...]
> AttributeError: module 'diffusers' has no attribute 'StableDiffusionXLPipeline'

**Comment by IDSG** [comment]
I have the same problem, any update on this?

**Comment by ch1ckenstripper** [comment]
Updated extension, now it works. THANKS!
