### ISSUE TITLE
Files not being saved with prompt words, even with a simple prompt containing no funky characters...

### ISSUE THREAD

**Issue by ch1ckenstripper** [lifeisboringsoprogramming/sd-webui-xldemo-txt2img#8]
Hey its not a huge deal but here is the output for the error: THANKS

*** Error adding [prompt_words] to filename
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\images.py", line 462, in apply
        replacement = fun(self, *pattern_args)
      File "E:\AI\stable-diffusion-webui\modules\images.py", line 368, in <lambda>
        'prompt_words': lambda self: self.prompt_words(),
      File "E:\AI\stable-diffusion-webui\modules\images.py", line 418, in prompt_words
        words = [x for x in re_nonletters.split(self.prompt or "") if x]
    TypeError: expected string or bytes-like object

---

**Comment by lifeisboringsoprogramming** [comment]
what version are you using?
my testing environment is

Automatic1111 WebUI version: v1.4.0
python: 3.10.9
torch: 2.0.1+cu118
xformers: 0.0.20
gradio: 3.32.0
checkpoint: 20af92d769

**Comment by ch1ckenstripper** [comment]
heya my setup is on windows with

auto1111: 1.4.0
python: 3.10.6
torch: 2.0.1+cu118
xformers: 0.0.20
gradio: 3.32.0
checkpoint is whatever one downloads automatically (all .bin files?)
